Repository couchbasecloud/terraform-provider-couchbase-capella, pull requests merged in 2025-09, with the labels that each got.

#385 [AV-104546] Add import filter schema
  internal/provider/provider.go
  internal/resources/import_filter.go
  internal/resources/import_filter_schema.go
  internal/schema/import_filter.go
Labels: enhancement, needs-triage

#389 [AV-104548] Add import filter resource implementation
  examples/import_filter/README.md
  examples/import_filter/create_import_filter.tf
  examples/import_filter/get_import_filter.tf
  examples/import_filter/main.tf
  examples/import_filter/terraform.template.tfvars
  examples/import_filter/variables.tf
  examples/resources/couchbase-capella_import_filter/import.sh
  examples/resources/couchbase-capella_import_filter/resource.tf
  internal/api/client.go
  internal/errors/errors.go
  internal/resources/import_filter.go
  internal/resources/import_filter_schema.go
  internal/schema/import_filter.go
  internal/schema/validate.go
Labels: enhancement

#390 [AV-104559] App Endpoint Access Control Function
  examples/access_control_function/README.md
  examples/access_control_function/create_access_control_function.tf
  examples/access_control_function/main.tf
  examples/access_control_function/terraform.template.tfvars
  examples/access_control_function/variables.tf
  internal/errors/errors.go
  internal/provider/provider.go
  internal/resources/app_endpoint_access_control_function.go
  internal/resources/app_endpoint_access_control_function_schema.go
  internal/schema/app_endpoint_access_function.go
Labels: enhancement

#402 [AV-111247] Do not set bucket defaults in provider
  internal/resources/bucket.go
  internal/resources/bucket_schema.go
Labels: bug

#403 [AV-104553] Add single app endpoint datasource
  internal/datasources/app_endpoint.go
  internal/datasources/app_endpoint_schema.go
  internal/datasources/app_endpoints.go
  internal/datasources/app_endpoints_schema.go
  internal/provider/provider.go
Labels: enhancement, needs-triage

#408 [AV-111501] Filter app endpoints by name
  internal/datasources/app_endpoints.go
  internal/datasources/app_endpoints_schema.go
  internal/schema/app_endpoint.go
Labels: enhancement
