Repository couchbasecloud/terraform-provider-couchbase-capella, pull requests merged in 2025-07, with the labels that each got.

#351 [AV-103003] Create common app service for acc tests
  Makefile
  acceptance_tests/app_service.go
  acceptance_tests/appservice_acceptance_test.go
  acceptance_tests/cluster.go
  acceptance_tests/globals.go
  acceptance_tests/setup_test.go
  internal/api/cluster/cloud_provider.go
Labels: enhancement

#360 [AV-105195] Add common functions for converting basetype strings and strings
  Makefile
  acceptance_tests/app_service.go
  acceptance_tests/appservice_acceptance_test.go
  acceptance_tests/cluster.go
  acceptance_tests/globals.go
  acceptance_tests/setup_test.go
  docs/index.md
  examples/app_services_cidr/README.md
  examples/app_services_cidr/create_allowlist.tf
  examples/app_services_cidr/list_allowlists.tf
  examples/app_services_cidr/main.tf
  examples/app_services_cidr/terraform.template.tfvars
  examples/app_services_cidr/variables.tf
  examples/data-sources/couchbase-capella_app_services_cidr/data-source.tf
  examples/getting_started/app_services_cidr.tf
  examples/resources/couchbase-capella_app_services_cidr/import.sh
  examples/resources/couchbase-capella_app_services_cidr/resource.tf
  internal/api/app_services_cidr.go
  internal/api/cluster/cloud_provider.go
  internal/datasources/app_services_cidr.go
  internal/errors/errors.go
  internal/provider/provider.go
  internal/resources/apikey.go
  internal/resources/app_service_cidr.go
  internal/resources/app_service_cidr_schema.go
  internal/resources/cluster.go
  internal/resources/user.go
  internal/schema/apikey.go
  internal/schema/app_service_cidr.go
  internal/schema/types.go
  internal/schema/types_test.go
  internal/schema/user.go
Labels: enhancement, needs-triage

#350 [AV-102723] Initialize num_replica to null
  acceptance_tests/gsi_accpetance_test.go
  examples/getting_started/gsi.tf
  examples/getting_started/terraform.template.tfvars
  examples/getting_started/variables.tf
  internal/resources/gsi.go
Labels: bug

#357 [AV-104294] Consume 504 gateway error
  internal/api/client.go
  internal/api/error.go
  internal/errors/errors.go
  internal/resources/gsi.go
Labels: enhancement

#365 [AV-106890] Upgrade guide
  docs/guides/1.5.2-upgrade-guide.md
Labels: documentation

#366 [AV-107162] Do not allow setting autoexpansion for AWS/GCP
  acceptance_tests/cluster_acceptance_test.go
  internal/resources/cluster.go
  internal/resources/cluster_schema.go
Labels: bug
