Repository couchbasecloud/terraform-provider-couchbase-capella, pull requests merged in 2025-08, with the labels that each got.

#369 [AV-107267] Restrict setting IOPS for GCP clusters
  acceptance_tests/cluster_acceptance_test.go
  internal/errors/errors.go
  internal/resources/cluster.go
  internal/resources/cluster_schema.go
Labels: bug

#368 [AV-107269] Add change log for v1.5.3
  .github_changelog_generator
  CHANGELOG.md
  docs/guides/1.5.3-upgrade-guide.md
  docs/index.md
Labels: documentation

#377 [AV-108158] Remove cluster ID arg from import command in examples readme
  examples/cluster/README.md
Labels: needs-triage

#379 [AV-104556] Add Access function schema
  internal/provider/provider.go
  internal/resources/access_function.go
  internal/resources/access_function_schema.go
  internal/schema/access_function.go
Labels: enhancement, needs-triage
